### ISSUE TITLE
Nested routes?

### ISSUE THREAD

**Issue by ivanbara** [kazzkiq/svero#10]
Could you please add an example how to use nested routes?

**Comment by kazzkiq** [comment]
As described in #3, there isn't support for nested/sub routes yet.

**Comment by ivanbara** [comment]
Are you planning to add support?

**Comment by kazzkiq** [comment]
May be eventually added eventually, but I don't have plans to do so in the short term.

**Comment by bigjoevtrj** [comment]
+1

**Comment by pateketrueke** [comment]
Hello, I recently sent #19 to deal with something similar.

Do you guys think that could help?

**Comment by bigjoevtrj** [comment]
> Hello, I recently sent #19 to deal with something similar.
> 
> Do you guys think that could help?

Just use svelte-routing instead...it deals with nested routes like a Boss!

**Comment by pateketrueke** [comment]
> Just use svelte-routing instead...it deals with nested routes like a Boss!

Actually I tried it, but it was not able to handle nested-routes like "/login#section" as I mentioned on the PR.

I like smaller libs and svero is very small in comparison both on size and features. 👍

**Comment by bigjoevtrj** [comment]
> > Just use svelte-routing instead...it deals with nested routes like a Boss!
> 
> Actually I tried it, but it was not able to handle nested-routes like "/login#section" as I mentioned on the PR.
> 
> I like smaller libs and svero is very small in comparison both on size and features.

Generally mixed history types i.e. Hash & Browser are used to handle situations where we need to have old code (server side) and implement client side code.

**Comment by pateketrueke** [comment]
I'm using _hash-based routing_ for handle some UI states, not routing per-se.

**Comment by frederikhors** [comment]
@pateketrueke have you found a way? I need the same: "hash-based routing for handle some UI states".

Useful for something like `List > Detail` scenario.

**Comment by pateketrueke** [comment]
Hi @frederikhors yeah, I found something!

I'm integrating the last details, I'll update my PR for that soon.
