### ISSUE TITLE
Render <slot> instead if component is not given?

### ISSUE THREAD

**Issue by pateketrueke** [kazzkiq/svero#17]
It would be nice o support this:

```html
<Route path="/test">
  <h1>It works!</h1>
</Route>
```

If you're OK with this I'll open a PR for it.

Thank you!

**Comment by frederikhors** [comment]
@pateketrueke go with PR! :)

**Comment by kazzkiq** [comment]
@pateketrueke I see no problem in enabling this feature. Would love a PR with it!

**Comment by frederikhors** [comment]
I think we should add docs at least in Readme.md.
