### ISSUE TITLE
Path params with component prop

### ISSUE THREAD

**Issue by uriberto** [kazzkiq/svero#20]
A component inside a Route seems to be includable via either
1) component={About}
or
2) Using the slot as in `<Route ... ><About/></Route>`

In 1, it doesn't seem possible to pass "About" any props of my own.
In 2, it doesn't seem possible to access router.params.

Is it possible to allow both of these at once?

**Comment by pateketrueke** [comment]
Hello, can I help?

1. We can pass additional `props` to the underlying component, e.g.

```html
a) <Route props={myProps} component={About} />
b) <Route {...myProps} component={About} />
```

> Both styles can work, but currently `svero` does not supports it... a PR would be needed for.

2. Currently is not supported, when `<slot />` support was added I just forgot to pass the `router` prop to it.

> A fix for this is on #19 so it can be landed soon.
