### ISSUE TITLE
Lazy loading routes and router hooks

### ISSUE THREAD

**Issue by ansarizafar** [kazzkiq/svero#21]
Lazy loading is very important for bundle size. Does Svero supports lazy route loading? How can I display a progress bar during route loading? Is there any plan to add router hooks?

**Comment by kazzkiq** [comment]
If by lazy loading you mean code-splitting (a route's code is only loaded if it's called by the URL), then the answer is no.

If  you need that level of control over what your client receives in terms of bundle size, you should try using a fully featured framework such as [Sapper](https://github.com/sveltejs/sapper).

**Comment by JohnnyFun** [comment]
I bet you could work around it and make the "Route" component call `import(...).then(dynamicComponent => ...)` and then use `<svelte:component this={dynamicComponent.default}/>`?
