### ISSUE TITLE
"'watchQuery' of undefined" error using a routing solution. Maybe we need to wait "setClient(client)"?

### ISSUE THREAD

**Issue by frederikhors** [kazzkiq/svero#22]
I think I found a bug.

I still don't know if the bug is caused by `svelte-apollo` (https://github.com/timhall/svelte-apollo/) or what I'm using for routing in this project: `svero`.

**PROBLEM REPRODUCTION**: https://codesandbox.io/s/bzix3

In codesandbox there are still some problems with Svelte (or maybe I'm the problem) but it doesn't work. You have to download it and run with: `npm i && npm run dev`.

**THE PROBLEM**:

If I go to `http://localhost:5000/` the Home Page is correctly displayed.

If I go to `http://localhost:5000/articles` **USING THE LINK!!!** the Articles Page is correctly displayed.

If now I reload the page I get this error in browser console:

```log
svelte-apollo.es.js:51 Uncaught TypeError: Cannot read property 'watchQuery' of undefined
    at query (svelte-apollo.es.js:51)
    at instance$3 (ArticlesPage.svelte:14)
    at init (internal.mjs:1395)
    at new ArticlesPage (ArticlesPage.svelte:14)
    at updateComponent (Router.svelte:24)
    at handleRoute (Router.svelte:65)
    at Router.svelte:76
    at Array.some (<anonymous>)
    at handlePopState (Router.svelte:70)
```

If I use `console.log(client)` just after `ArticlesPage.svelte` line 13 (`const client = getClient();`) I can see the client is indeed `undefined`.

Maybe we have to wait for `setClient(client)` in the `App.svelte` file to finish is job?

**Comment by frederikhors** [comment]
@kazzkiq sorry for this ping. Some idea?

**Comment by kazzkiq** [comment]
@frederikhors The error stacktrace doesn't belong to svero code. The only thing I can think of is for you to check if all your code is being executed inside `onMount` to prevent lifecycle errors.

Further than that, I would need to dive into your code and perhaps `svelte-apollo` to debug it, which I can't do at the moment.

**Comment by frederikhors** [comment]
Yes, if I use something like this it works:

```js
let isLoaded = false;
  onMount(() => {
    setTimeout(() => {
      isLoaded = true;
    });
  });
```

But as you know it's an hack!

**Comment by frederikhors** [comment]
@kazziq, the same question in the `svelte-apollo` repo (here: https://github.com/timhall/svelte-apollo/issues/16#issuecomment-496747893) could change your mind about an aspect of Svero.

> After digging through the svero code I think the issue is that it renders components with `new Component` which does not pass context down to the child routes. I’m not quite sure how it works on navigate, but not refresh, but I think that’s the issue.

What do you think about?

**Comment by pateketrueke** [comment]
Hi @frederikhors , the race condiction from `getClient()`can be solved if you set `<script context="module">` on your `App.svelte` component.

That way the client gets correctly initialized, and then you can call `getClient()` without issues.

**Comment by pateketrueke** [comment]
Hi @frederikhors I've been investigating about this and I don't think `new Component` has problems, even actually switching to `<svelte:component ... />` the issue persists.

I just tried your example using `svelte-routing` and seems to be working, idk why is not working this side yet...

**Comment by pateketrueke** [comment]
I found the reason behind this issue, we need to provide the `svelte` entry on the package.json and also the package dependencies, e.g. `abstract-nested-router` (as for #19)

That's the only problem behind, once the package gets published correctly it will be consumed as expected.

@frederikhors try cloning your sandbox locally and then try `npm i pateketrueke/svero#feature/hash-router --save-dev` instead, now it will work! 🤔 

@kazzkiq the PR I've been working on already fixed this too, can you take a look? 🙏

**Comment by kazzkiq** [comment]
@pateketrueke Sure! Are you done on #19 or there still work to do? Want to review it as a whole once it gets finished. 👍

**Comment by pateketrueke** [comment]
@kazzkiq I think is ready for review. 🍻

**Comment by pateketrueke** [comment]
Most of these context-issues are solved by properly consuming this package, so as long your bundler understand the `svelte` entry, or they're pointing to ESM sources I think it'll be fine.

So, I believe we can close this issue. 🍻

**Comment by kazzkiq** [comment]
Closing now, if any other error related appears and we deem necessary, I reopen it.
