### ISSUE TITLE
Cannot apply styles to link

### ISSUE THREAD

**Issue by tcaer** [kazzkiq/svero#25]
Hi,

I am using the Link components like so: `<Link href='/' className='someclass'>Some text</Link>` and cannot figure out how to apply styles to it. I setup a `<style></style>` area and apply a style for the `someclass` class like so:
```
<style>
.someclass {
color: red;
}
</style>
```
The problem is that the styles aren't applied to the element. Normally Svelte generates local class names which hold the styles but none are generated for the link. Other regular elements like `divs` do get their local class names generated and styles properly applied. I also tried using `Link href='/' class='someclass'>Some text</Link>` with no luck either.

Thanks

**Comment by kazzkiq** [comment]
Svelte don't let you pass scoped styles to children components at the moment.

This means that for your style to work you have to use `:global()`, like this:

```css
<style>
  :global(.someclass) {
    color: red;
  }
</style>
```

**Comment by tcaer** [comment]
Another solution is to wrap a `<p>` with all the styles inside of the `<Link>` element like so: `<Link href='/'><p class='someclass'>some text</p></Link`. In this case, the styles will work properly without the use of the css `:global()` selector.
