### ISSUE TITLE
Any plan to implement a layout system?

### ISSUE THREAD

**Issue by chainlist** [kazzkiq/svero#29]
All is in the title!

Would like to display different layout based on the route we're on.

And already tried about doing it in my component, but the layout is being refresh when navigating from route to route.

**Comment by pateketrueke** [comment]
> And already tried about doing it in my component, but the layout is being refresh when navigating from route to route.

Hi @chainlist, recently we released a major version of `svero`.

Can you try again with this version? Also, it would be nice to see what you tried to understand better.

**Comment by kazzkiq** [comment]
Closing this as there were no more details to the issue. Once code and/or examples are provided, the Issue may be reopen.
