### ISSUE TITLE
Is there support for handling query string?

### ISSUE THREAD

**Issue by harfangk** [kazzkiq/svero#33]
Svero doesn't seem to support automatically parsing and adding query string into `router` object. With the support, loading `https://github.com/kazzkiq/svero/issues/new?foo=bar` would add `"foo": "bar"` somewhere in the `router`.

It's a bit annoying to implement along with fragment based routing, but it could be handy!

**Comment by pateketrueke** [comment]
Just read-only queryParams or also a way to create links from objects that supports them? 🤔

**Comment by harfangk** [comment]
For completeness's sake implementing both would be better. It would make little sense to support accessing query strings but not setting them in <Link>s.

**Comment by pateketrueke** [comment]
Thank you. I think it'll take its time, any hint for starting to look at?

**Comment by pateketrueke** [comment]
Hi, if you want you can try [yrv](https://github.com/pateketrueke/yrv) as a drop-in replacement to svero, thank you!

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
