### ISSUE TITLE
Does not work with Webpack

### ISSUE THREAD

**Issue by artecoop** [kazzkiq/svero#34]
Hello!
I'm trying to use svero with svelte webpack and it does not work

Steps: 
- npx degit sveltejs/template-webpack svelte-app
- cd svelte-app
- modify webpack.config.js to handle 404 by adding 
```
devServer: {
    historyApiFallback: true
}
```
- npm i
- npm install --save svero
- create folder pages in src
- create file pages/Index.svelte (and add simple html like `<h2>Hey</h2>`)
- create file pages/About.svelte (and add simple html like `<h2>About</h2>`)
- in App.svelte
```
<script>
	import { Router, Route } from 'svero';

	import Index from './pages/Index.svelte';
	import About from './pages/About.svelte';
</script>

<h1>Hello Svelte!</h1>

<Router>
	<Route path="/" component={Index} />
	<Route path="/about" component={About} />
	<Route path="/about/:who/123/:where" component={About} />
</Router>
```
If you point to http://localhost:8080/about
it renders both Index and About

**Comment by kazzkiq** [comment]
The issue doesn't seem to be Webpack, but `v1.0.0`.

Please use `v0.5.0` (`npm install --save svero@0.5.0`) while we do further investigation.

@pateketrueke perhaps this bug was introduced in PR #19?

**Comment by pateketrueke** [comment]
Hi @artecoop you need to add `exact` to the `path="/"` route, that's why the nested behaviour will load all segments from any given path.

Also, you don't need to match `About` component twice, e.g.

```html
<script>
  import { Router, Route, Link } from 'svero';

  import Index from './pages/Index.svelte';
  import About from './pages/About.svelte';
</script>

<h1>Hello Svelte!</h1>

<!-- possible links -->
<Link href="/">Home</Link>
<Link href="/about">About</Link>
<Link href="/about/foo">About who?</Link>
<Link href="/about/foo/123">About who?</Link>
<Link href="/about/foo/123/bar">About who?</Link>

<!-- actual routes -->
<Router>
  <Route path="/" exact component={Index} />
  <Route path="/about/:who/123/:where" component={About} />
</Router>
```

In such case, `About` must be aware of params injected:

```html
<script>
  export let router = {};
</script>

<h2>About</h2>
<pre>{JSON.stringify(router.params, null, 2)}</pre>
```

Please let me know if this satisfy your needs, so much thanks for your feedback!

**Comment by artecoop** [comment]
@pateketrueke I can confirm that with your suggestions, even with version 1.0.0, it works
Thanks!
