### ISSUE TITLE
On component destroy routes with params leads to uncaught exception in promise

### ISSUE THREAD

**Issue by DiverOfDark** [kazzkiq/svero#35]
Example:

```
<script>
	import { Router, Route } from 'svero'
	
	let flag = true;
</script>

{#if flag}
<Router>
	<Route path="/">123</Route>
	<Route path="/A">234</Route>
	<Route path="/A/:param">345</Route>
</Router>
{/if}

<button on:click="{() => flag = false}">
	test
</button>
```

After clicking on button it throws uncaught exception in promise:
```
defaultExport {message: "Unreachable '/A/:param', segment '/A' is not defined"}
```

**Comment by pateketrueke** [comment]
Nice catch, let me figure out if this is actually an issue or not... thank you!

**Comment by pateketrueke** [comment]
Yeah... it is, seems like pending work after destroy.

I believe adding a `onDestroy` handler on `<Router />` for cleanup would work.

**Comment by pateketrueke** [comment]
Hi, if you want you can try [yrv](https://github.com/pateketrueke/yrv) as a drop-in replacement to svero, thank you!

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
