### ISSUE TITLE
Svero is picking the wrong component

### ISSUE THREAD

**Issue by lud** [kazzkiq/svero#36]
With this code:
```
<Router>
  <Route path="/game/parties/:party_id" component={Party} />
  <Route path="/game/new-party" component={PartyCreate} />
  <Route path="/game" component={Dashboard} />
</Router>
```

When I load the page as `/game`, the `Party` component is initialized (with `undefined` as `party_id`.

`resolveRoutes` returns:
```
[
  {
    "matches": true,
    "params": {},
    "route": "/",
    "path": "/"
  },
  {
    "matches": false,
    "params": {},
    "route": "/",
    "path": "/"
  },
  {
    "key": "p23gll8y2o",
    "matches": true,
    "params": {},
    "route": "/game",
    "path": "/game"
  }
]
```

I know I can use a basePath for the moment, but I may have urls not starting with `/game` to handle.

What did I do wrong ?

**Comment by kazzkiq** [comment]
Try using the `exact` attribute:

```html
<Router>
  <Route path="/game/parties/:party_id" component={Party} />
  <Route path="/game/new-party" component={PartyCreate} />
  <Route exact path="/game" component={Dashboard} />
</Router>
```

If that doesn't work, try putting `/game` route before all other routes, too.

**Comment by lud** [comment]
Sorry for the late answer, I changed project, but thank you that is good to know.
