### ISSUE TITLE
Problem with exact prop on <Route/>

### ISSUE THREAD

**Issue by LaughingBubba** [kazzkiq/svero#39]
I don't think exact pathing is working as expected.

Given the following routes from `App.svelte`, I would expect `/stooges` to render the `<Stooges/>` component and `/stooges/add` to *only* render the `<AddStooges/>` component. Instead it renders both `<Stooges/>` *and* `<AddStooges/>`.

Further more, I would expect that `/stooges/non-existent` would only render `<h1>404 - Not Found</h1>` but it also renders `<Stooges/>`.

```html
<Router>

	<!-- <Route exact path='/stooges/add' component={AddStooge}/> -->
	<Route exact path='/stooges' component={Stooges}/>
	<Route exact path='/stooges/add' component={AddStooge}/>
	
	<Route fallback path='*'>
		<h1>404 - Not Found</h1>
	</Route>

</Router>
```
Unless I'm missing something? I have an example at this [repo](https://github.com/LaughingBubba/svero-example.git).

EDIT: I've add a `svelte-routing` branch which demo's the expected behavior.

**Comment by kazzkiq** [comment]
Managed to replicate this issue. It's indeed a bug and also happens with `:param` routes.

e.g.

```html
<Router>
  <Route exact path='/stooges' component={Stooges}/>
  <Route exact path='/stooges/:id' component={AddStooge}/>
</Router>
```

In the example above, visiting `/stooges/123` would result in both routes being rendered in the page.

**Comment by pateketrueke** [comment]
I sorted out this issue through the abstract-nested-router, in effect, exact routes were not handled as expected... so I fixed that and published a patched version.

Now `exact` routes work as we're expecting, just notice that routes with splat-params like `/foo/*bar` cannot be exact...

@LaughingBubba I tested out the "stooges" example with these new changes, can you confirm please? Thank you!

**Comment by LaughingBubba** [comment]
@pateketrueke Hi just saw your message. I've got a few things on ATM but will double check in the next couple of days.

**Comment by pateketrueke** [comment]
@LaughingBubba  if you want you can try [yrv](https://github.com/pateketrueke/yrv) as a drop-in replacement to svero, thank you!

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
