### ISSUE TITLE
Svero on official Svelte 3 FAQ

### ISSUE THREAD

**Issue by frederikhors** [kazzkiq/svero#4]
Svero is on official Svelte 3 FAQ now: https://github.com/sveltejs/svelte/issues/2669 and https://github.com/sveltejs/svelte/wiki/FAQ#is-there-a-routing-solution.

Thanks for your work, @kazzkiq.

**Comment by kazzkiq** [comment]
Thanks! Glad to see it being useful to others as much as it was to me. 👍
