### ISSUE TITLE
Issue in path="*" for site root

### ISSUE THREAD

**Issue by timgblack** [kazzkiq/svero#43]
Starting a new project (using svero@1.0.0), I set up my initial route as `<Route path="*" component={MainPage} />` as I have done to great success in a previous project (running @0.5.0).

This rendered no route for the site root / (both Firefox and Chrome treat it as an empty string), but happily displayed the main page (currently just the text "Main Page") on every page, including other valid routes next to their contents.

Comments in open issues lead me to `<Route exact path="" fallback component={MainPage} />` which does do what I want it to do, but is not as clear as `path="*"` and is not clearly documented in the readme.

As well as determining whether this is unintended, I'd appreciate any advice on whether `exact` should be applied to only the one route, all routes, only routes without a placeholder or even no routes at all as I'm not doing any nesting. The readme is informative but not super clear on this point.

**Comment by pateketrueke** [comment]
We really appreciate your feedback @timgblack and of course we'll address this issue on our documentation asap, thank you!

**Comment by pateketrueke** [comment]
Update: I opened a PR that actually solves a `exact` related issue, see #44 for more info...

tl-dr; `exact` routes can be applied on all routes, if none is exact then they'll be loaded in cascade... otherwise, just those routes set as `exact` will be loaded.

Using `exact path="" fallback` will not longer work.

**Comment by LeandroBarone** [comment]
I think there may be some kind of misunderstanding. This bug report is not primarily about documentation or the `exact ` keyword. It is about the route with `path="*"` not showing up when the path is empty. I also have this problem and I think it is a bug.

**Comment by pateketrueke** [comment]
Oh, I understand now.

Let me see what can I do, anyway it'll take a time to review/merge.

**Comment by mikemaccana** [comment]
Getting the same behavior here = `<Route path="*" component={FrontPage} />` won't render `FrontPage`. Svereo 1.0.0.

**Comment by mikemaccana** [comment]
(also @timgblack's workaround works for me, thanks Tim - obviously the proper solution is to actually fix it though)

**Comment by pateketrueke** [comment]
Hi, I just forked `svero` and rewrote major part of it to solve those issues and such: [yrv](https://github.com/pateketrueke/yrv)

You may think on `yrv` as an spiritual sucessor, please give it a try!

**Comment by mikemaccana** [comment]
@pateketrueke that's really cool! That said, maybe you should send a PR to @kazzkiq first? It would be better to try and have all your awesome stuff in the mainline Svero if possible!

**Comment by pateketrueke** [comment]
Yeah, I'll open a PR with the fixes and such once the activity on this repo gets back. 🍻

**Comment by mikemaccana** [comment]
Wouldn't submitting your PR create activity on this repo? 🤔

**Comment by pateketrueke** [comment]
I mean, activity from the author, since there are no official contributors no one else can review(?), approve/merge, etc.

**Comment by mikemaccana** [comment]
Just sent the PR. If they don't respond in time then the project is officially unmaintained and you have good reason to fork!

Pardon if I seen weirdly confident here I've been doing OSS for 20 years now and I'm pretty confident about community norms.

**Comment by Cldfire** [comment]
Chiming in to say I just bumped into this issue and it took me a good few minutes to figure out what was wrong. Would be great to see it fixed! :)

**Comment by pateketrueke** [comment]
Hi, @Cldfire  if you want you can try [yrv](https://github.com/pateketrueke/yrv) as a drop-in replacement to svero, thank you!

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
