### ISSUE TITLE
trouble with spa nested routing

### ISSUE THREAD

**Issue by wolfispace** [kazzkiq/svero#46]
im having trouble with the spa routing

when i have two routes like this
`<Route path="#" component={Home}/>`
`<Route path="#/about" component={About}/>`

and i want to display #/about the page renders the first route # **and** #/about

it should only render #/about

**Comment by pateketrueke** [comment]
Try adding the `exact` attribute on both Routes, if that does not work please let me know! :beers:

**Comment by wolfispace** [comment]
@pateketrueke thank you! that solved it :)
