### ISSUE TITLE
path="*": it doesn't react to path changes.

### ISSUE THREAD

**Issue by raguay** [kazzkiq/svero#49]
I'm using the following:

```html
<Route fallback path="*" component={Page} />
```

To send routes to the Page component that will lookup the path and see if there is a corresponding markdown file. If there is, it renders it. But, the Page component isn't getting anything when I go to one page and then another that would match it. If I go the a page that is a different component with it's own path, it changes fine. But, going from two pages that would match the above rule does absolutely nothing.

**Comment by raguay** [comment]
An interesting twist: if the path is '/blog/item' and the next click is to '/item', then the page does change. Both routes are picked up with the `*` component. If two routes are on the same "level", then the page doesn't refresh.

**Comment by pateketrueke** [comment]
Hi, can you help me to setup a gist to understand this better?

**Comment by raguay** [comment]
A gist will not help. Just create a site with the contents for the wildcard
route depending upon the address of the wildcard route. When you go from
one wildcard route to another, the contents will not change. But, if you go
from a fixed route to a wildcard route, it is always fine. This library is
designed for the wildcard/catch all else route to simply be a 404 type
page. But, I want to use it to send all other routes to a component that
gets a page from the file system depending on the route.

Richard

**Comment by pateketrueke** [comment]
I'm trying to understand but I'm not able to reproduce your application, sorry.

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
