### ISSUE TITLE
Demo or Example folder

### ISSUE THREAD

**Issue by frederikhors** [kazzkiq/svero#5]
Can we create a "Demo" or "Example" folder with many resources?

E.g. an integration with official https://github.com/sveltejs/template?

Thanks.

**Comment by kazzkiq** [comment]
You can use the [`/test`](https://github.com/kazzkiq/svero/tree/master/test) folder as an example.

This folder setups a Svelte 3 app featuring svero and basically all its functionalities.

The Rollup config file for this folder is located at root, named `rollup.config.test.js`.
