### ISSUE TITLE
All page components are displayed   (question)

### ISSUE THREAD

**Issue by colesico** [kazzkiq/svero#53]
```
// App.svelte
<script>
 // v1.0.0
  import { Router, Route } from "svero";

  import CreateTrademark from "./pages/trademark/CreateTrademark.svelte";
  import UpdateTrademark from "./pages/trademark/UpdateTrademark.svelte";
  import CreateEmbroidery from "./pages/embroidery/CreateEmbroidery.svelte";
</script>

<Router path="/directory">
  <Route path="/embroidery/create" component={CreateEmbroidery} />
  <Route path="/trademark/update" component={UpdateTrademark} />
  <Route path="/trademark/create" component={CreateTrademark} />
</Router>
```

If navigate to  `http:.. /directory/trademark/create`, then not only `CreateTrademark`  component is displayed, but also all  previous components  in <Router ..>(CreateEmbroidery,UpdateTrademark,CreateTrademark).

How can I specify to only the CreateTrademark component corresponding to the requested url is displayed?

**Comment by kazzkiq** [comment]
Can you please add `exact` attribute to your routes and check if the issue is solved?

e.g.

```html
<Router path="/directory">
  <Route exact path="/embroidery/create" component={CreateEmbroidery} />
  <Route exact path="/trademark/update" component={UpdateTrademark} />
  <Route exact path="/trademark/create" component={CreateTrademark} />
</Router>
```

**Comment by pateketrueke** [comment]
Yeah, that solves the issue... but it should not be necessary, `exact` is meant only for stop rendering of parent routes if child routes has exact matches. 🤔 

Let me see what can I do, thanks for your feedback!

**Comment by pateketrueke** [comment]
I found the root-cause of the problem and sent a PR to solve it. :beers:

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
