### ISSUE TITLE
Thoughts on Svero 2.0

### ISSUE THREAD

**Issue by kazzkiq** [kazzkiq/svero#54]
When I first drafted this project, there were almost no Svelte-based routes around. Svelte 3 was brand new, and I felt the need to have an easy, lean and simple way to actually handle routes using Svelte own component's syntax.

It's been some time now and there are plenty of Svelte-based route projects around. Some focusing on speed, others on bundle size, and others on having lot's of features and complexity. Meanwhile, it seems to me that Svero tried to embrace every aspect of a successful router, aiming at all sides, but barely hitting any.

That being said, I believe it's time to define the future of Svero and it's 2.0 version, and this is what I think it should **not** be:

1. Svero should not be a Svelte equivalent to react-router;
2. Svero should not be bounded by react-router API/nomenclatures;
3. Svero should not focus on advanced router features (nesting, super-crazy regex routes, hash subroutes, etc).

What I think Svero **should** be:

1. A simple and reliable library for routing in Svelte 3;
2. As lean and small as possible without having to opt-out of Svelte syntax;
3. Something focused for projects without advanced and fancy routing requirements.

With all that being said, I will start working on the new 2.0 version that may end up dropping some features, adding others, and making the library simpler, smaller and reliable. For those who feel the need to use something more robust, here is a list of alternatives:

- [abstract-state-router](https://github.com/TehShrike/abstract-state-router)
- [svelte-routing](https://github.com/EmilTholin/svelte-routing)
- [yrv](https://github.com/pateketrueke/yrv)
- [svelte-spa-router](https://github.com/ItalyPaleAle/svelte-spa-router)

**Comment by colesico** [comment]
Totally agree with this. Nesting, regex routes, hash subroutine is not so frequently used features. Simple fast and small router with basic routing support imho that's what the good router have to do

**Comment by pateketrueke** [comment]
Do you have a plan for it? Issues/PRs are starting to accumulate @kazzkiq

**Comment by kazzkiq** [comment]
I will only have time to work on 2.0 in the next month, just can't promise anything before due to lack of time, has been quite a year.

**Comment by elimisteve** [comment]
React Router is nothing but trouble! Please make the equivalent of Reach Router instead: https://reach.tech/router

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
