### ISSUE TITLE
How to handle a "back" button?

### ISSUE THREAD

**Issue by fjanon** [kazzkiq/svero#59]
I have a "Help" page with a "close" button that I would like to redirect to the previous page.

Is there a way to do that with svero?

I would like to do it either with a "Link" or a redirect call.

Thanks

**Comment by pateketrueke** [comment]
At this moment there's no built-in way to do that, you may opt to call `history.back()` as click handler.

**Comment by fjanon** [comment]
OK, thanks.

It might be a good feature to add in the future.
