### ISSUE TITLE
[Question] I'm always getting a 404 status code

### ISSUE THREAD

**Issue by Betelgeuse1** [kazzkiq/svero#63]
I don't understand if I'm doing something wrong or if it is an issue.

I wanted to try out svero, so I copied the example code, but if I try to access whatever endpoint that is not '/', I get a 404 status code, and nothing appears.

Here is my App.svelte file:
```svelte
<script>
  import { Router, Route } from 'svero';

  import About from './pages/About.svelte';

</script>

<Router>
  <Route path="/about" component={About} />
</Router>
```

and here is my About.svelte file:
```svelte
<script>
  export let router = {};
</script>

<h1>Hello World</h1>
```

I'm using svelte 3.15.0 and svero 1.0.0

**Comment by c0ldra1n** [comment]
Does the debugger console show anything? If so, please check #62 as svero doesn't seem to support svelte 3.15.0.

**Comment by Betelgeuse1** [comment]
Yes, when I'm going to /about I'm getting an error, but downgrading svelte to version 3.14, 3.10 or even 3 didn't fix the issue

The error:

```
The character encoding of the plain text document was not declared. 
The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. 
The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```

**Comment by pateketrueke** [comment]
It's very important to know which setup you're using, are you using rollup? webpack? using a static web-server?

I mean, 404 errors are from http-servers, and this library should not affect that, unles you're behind a web-server.

BTW, you can use [yrv](https://github.com/pateketrueke/yrv) as a drop-in replacement to svero, it also works on the online REPL so you can explore the API online!

**Comment by kazzkiq** [comment]
Svero is now deprecated. Check #68 for alternatives.
