### ISSUE TITLE
<Link> does not get locally scoped CSS classes

### ISSUE THREAD

**Issue by n1313** [kazzkiq/svero#9]
Setting a `class` to a component in Svelte normally adds a special class that is used to make it locally scoped (see https://svelte.dev/docs#style). This doesn't work with `<Link>`.

This Svelte code:

```
<style>
  .link { color: red }
</style>
<a href="/link" class="link">Red link</a>
```

produces this result:

```
<style>
.link.svelte-13u2rmm { color: red }
</style>
<a href="/link" class="link svelte-13u2rmm">Red link</a>
```

This code:

```
<script>
  import { Link } from 'svero';
</script>
<style>
  .link { color: red }
</style>
<Link href="/link" className="link">Red link</Link>
```

produces this result:

```
<style>
.link.svelte-13u2rmm { color: red }
</style>
<a href="/link" class="link">Red link</a>
```

so the link stays unstyled.

**Comment by kazzkiq** [comment]
I don't think that's possible in Svelte at the moment (passing generated CSS classes down to nested components).

But you can achieve the styling by using `:global()` CSS modifier:

```html
<script>
  import { Link } from 'svero';
</script>
<style>
  div :global(.link) { color: red }
</style>
<div>
  <Link href="/link" className="link">Red link</Link>
</div>
```

**Comment by n1313** [comment]
Interesting... I'm new to Svelte and didn't know that this is not possible.

**Comment by kazzkiq** [comment]
Yep, the whole idea behind scoped CSS is that you get it stuck at your component level. If you really need to set it loose, you can use `:global()`, but there isn't much more than that.

You could always file an Issue in Svelte repo, if you believe that's an important feature.
